Fixes and fastclick addition
devgeniem/wp-starter-dustpress-theme pull request #14
Opened 2017-09-01 17:19 UTC by ironland

Fix code style errors. 
Add fastclick. 
Change theme.js to not use static class properties.

2017-09-11 13:03 UTC, Nomafin commented on assets/scripts/main.js
> +let FastClick = require( 'fastclick' );
const

2017-09-11 13:04 UTC, Nomafin requested changes

2017-09-11 13:04 UTC, Nomafin commented on assets/scripts/theme.js
>                  let className = globalControllers[i].name;
const

2017-09-11 13:04 UTC, Nomafin commented on assets/scripts/main.js
> +let FastClick = require( 'fastclick' );
const

2017-09-11 13:04 UTC, Nomafin commented on assets/scripts/theme.js
>                  let className = templateControllers[i].name;
const

2017-09-12 05:53 UTC, villesiltala approved these changes

2017-09-15 13:12 UTC, ironland commented
fikasttu muutospyynnöt ja mergetty

2017-09-15 13:21 UTC, Nomafin approved these changes
ok

2017-09-15 13:32 UTC, merged